#!/usr/bin/env python

import sys, os, getopt,glob

def main(argv) :
    """
    
    countFailedJobs
    
    count failed jobs per relval sample in failure-archive directory

    optional parameters                       :
    --help (-h)                               :       help
    --debug (-d)                              :       debug statements
    
    """

    debug              = 0

    samples = ['MinBias','10MuonsPt10','SingleMuPlusPt1000','SingleMuMinusPt1000','SingleMuPlusPt100','SingleMuMinusPt100','SingleMuPlusPt10','SingleMuMinusPt10','SingleEPt35','SingleTauPt35','SingleGammaPt35','SingleGammaPt10','TTbarL1','SingleMuPlusPt100L1','QCD_pt80_120L1','SingleEPt35L1','TTbar','ZPrimeDijets700','BJets50-120','CJets50-120','Z-EE','Z-MM','Z-TT','W-E','W-M','W-T','ChargedHiggsTausM200','HiggsPhotons120','Higgs-ZZ-4L','QCD_pt30_50','QCD_pt50_80','QCD_pt80_120','QCD_pt3000_3500','QCD_pt15_20','QCD_pt20_30','QCD_pt120_170','QCD_pt170_230','QCD_pt230_300']

    try:
        opts, args = getopt.getopt(argv, "", ["help", "debug"])
    except getopt.GetoptError:
        print main.__doc__
        sys.exit(2)

    # check command line parameter
    for opt, arg in opts :
        if opt == "--help" :
            print main.__doc__
            sys.exit()
        elif opt == "--debug" :
            debug = 1

    for sample in samples:
        files = glob.glob('*' + sample + '-*')
        print "%s: %6d files" % (sample.ljust(50),len(files))


if __name__ == '__main__' :
    main(sys.argv[1:])
