#!/usr/bin/env python2.4

import sys, os
import FWCore.ParameterSet.Config as cms

def main(argv) :
    """
    
    createMergeConfig <list of root files>
    
    create configuration to merge given root files

    configuration name: merge.py

    """

    inputFiles = []
    for file in argv:
        fullPath = os.path.abspath(file)
        if os.path.exists(fullPath):
            inputFiles.append("file:"+fullPath)

    process = cms.Process('Merge')

    process.source = cms.Source("PoolSource",
                                fileNames = cms.untracked.vstring(*inputFiles)
                                )

    process.output = cms.OutputModule("PoolOutputModule",
                                      fileName = cms.untracked.string('output.root'))
    
    process.out_step = cms.EndPath(process.output)

    output = open('merge.py','w')
    output.write('import FWCore.ParameterSet.Config as cms\n')
    output.write(process.dumpPython())
    output.close()


if __name__ == '__main__' :
    main(sys.argv[1:])

