#!/usr/bin/env python2.4
import sys, os, string, time, popen2

levels = ['no','0.05','0.1','0.15','0.2','0.25','0.3','0.35','0.4']

for index in range(30):

    for level in levels :

        identifier = 'single_mu_jet_3_' + str(index*0.1) + '_' + str((index+1)*0.1) + '_' + level

        output = level + ' ' + str(index*0.1) + ' ' + str((index+1)*0.1) + ' '

        logfilename = identifier + '.log'

        try:
            file = open(logfilename)

            for line in file.readlines() :
                if line.find('1 : ') == 0 :
                    output += line.split()[-2] + ' ' + line.split()[-1]

            cmd = 'root -q -l ' + identifier + '_histograms.root printNTracks.C'

            proc = popen2.Popen4(cmd)
            exit = proc.poll()
            lines = []
            while ( exit == -1 ) :
                lines += proc.fromchild.readlines()
                exit = proc.poll()
            output += ' ' + lines[-1].strip()

            print output
        except:
            print 'file:',logfilename,'cannot be opened'
