#!/usr/bin/env python2.4
import sys, os, string, time, popen2

file = open('do_0.4.sh','w')
file.write('#!/bin/bash\n')

for index in range(30):

    identifier = 'single_mu_jet_3_' + str(index*0.1) + '_' + str((index+1)*0.1) + '_0.4'

    file.write('cmsRun ' + identifier + '.cfg >& ' + identifier + '.log\n')

file.close()
