#!/usr/bin/env python2.4
import sys, os, string, time, popen2




for index in range(30):

    identifier = 'single_mu_jet_3_' + str(index*0.1) + '_' + str((index+1)*0.1) + '_0.4.cfg'

    try:
        file = open(identifier,'w')

        file.write('process R = {\n')
        file.write('  include "GutSoftConfigurations/Reconstruction/reconstruction.cff"\n')
        file.write('  replace gutSoftTrackingEventDisplay.OutputFileName = "single_mu_jet_3_' + str(index*0.1) + '_' + str((index+1)*0.1) + '_0.4"\n')
        file.write('  replace roadSearchSeeds.MergeSeedsCenterCut = 0.4\n')
        file.write('  replace roadSearchSeeds.MergeSeedsRadiusCut = 0.4\n')
        file.write('  include "GutSoftConfigurations/DataSets/cmssw_1_4_0_pre3_single_mu_jet_3_' + str(index*0.1) + '_' + str((index+1)*0.1) + '.cff"\n')
        file.write('  replace PoolSource.maxEvents  = 100\n')
        file.write('  replace PoolSource.skipEvents = 0\n')
        file.write('  replace GutSoftHistogramFileService.OutputFileName = "single_mu_jet_3_' + str(index*0.1) + '_' + str((index+1)*0.1) + '_0.4_histograms.root"\n')
        file.write('  replace out.fileName = "single_mu_jet_3_' + str(index*0.1) + '_' + str((index+1)*0.1) + '_0.4.root"\n')
        file.write('}\n')

        file.close()
    except :
        print 'Could not create parameter-set',identifier
