#!/usr/bin/python

import sys, os, getopt, popen2, fcntl, select, string, time

class Jobs:
    def __init__(self):
        self._jobArray = []
        return

    def report(self):
        print ''
        print ' PA LSF queue status'
        print ''
        print '    Number of jobs in queue: %4d pending: %4d running: %4d other: %4d' % (self.jobs(),self.jobs('Idle'),self.jobs('Running'),self.jobs('Other'))
        print ''
                
        return

    def status(self):
        array = [];
        for job in self._jobArray :
            if job.jobstatus() not in array:
                array.append(job.jobstatus())
        return array

    def holdcode(self, jobstatus='All'):
        array = [];
        for job in self._jobArray :
            if jobstatus == 'All' or job.jobstatus() == jobstatus :
                if job.holdcode() not in array:
                    array.append(job.holdcode())
        return array

    def holdreason(self, holdcode, holdsubcode) :
        for job in self._jobArray :
            if  job.holdcode() == holdcode :
                if job.holdsubcode() == holdsubcode :
                    return job.holdreason()
        return ''

    def holdsubcode(self, jobstatus='All', holdcode=-1):
        array = [];
        for job in self._jobArray :
            if jobstatus == 'All' or job.jobstatus() == jobstatus :
                if holdcode == -1 or job.holdcode() == holdcode :
                    if job.holdsubcode() not in array:
                        array.append(job.holdsubcode())
        return array

    def jobs(self, jobstatus='All', holdcode=-1, holdsubcode=-1):
        counter = 0
        for job in self._jobArray :
            if jobstatus == 'All' or job.jobstatus() == jobstatus :
                if holdcode == -1 or job.holdcode() == holdcode :
                    if holdsubcode == -1 or job.holdsubcode() == holdsubcode :
                        counter += job.counter()
        return counter

    def append(self, job):
        for existing in self._jobArray :
            if existing.compare(job) == 1 :
                existing.increaseCounter()
                return
        self._jobArray.append(job)
        return

class Job:
    def __init__(self, status, holdcode, holdsubcode, holdreason):
        self._status      = status
        self._holdcode    = holdcode
        self._holdsubcode = holdsubcode
        self._holdreason  = holdreason
        self._counter     = 1

        # JobStatus dictionary
        self._jobstatus = {}
        self._jobstatus[0] = 'Unexpanded'
        self._jobstatus[1] = 'Idle'
        self._jobstatus[2] = 'Running'
        self._jobstatus[3] = 'Removed'
        self._jobstatus[4] = 'Completed'
        self._jobstatus[5] = 'Other'
        self._jobstatus[6] = 'Submission_err'
        
        return

    def jobstatus(self) :
        return self._jobstatus[int(self._status)]

    def globusstatus(self) :
        return self._globusstatus[int(self._globus)]

    def report(self) :
        out = 'Jobs: '+str(self._counter)+' Status: '+self._jobstatus[int(self._status)]
        if int(self._status) == 5 :
            out += ' Code: '+str(self._holdcode)+' SubCode: '+str(self._holdsubcode)+' Reason: '+self._holdreason
        print out
        return

    def status(self):
        return self._status

    def holdcode(self):
        return self._holdcode

    def holdsubcode(self):
        return self._holdsubcode

    def holdreason(self):
        return self._holdreason

    def counter(self):
        return self._counter

    def increaseCounter(self) :
        self._counter += 1
        return

    def compare(self, second_job):
        return_value = 0
        if self._status == second_job.status() :
            if self._holdcode == second_job.holdcode() :
                if self._holdsubcode == second_job.holdsubcode() :
                    if self._holdreason == second_job.holdreason() :
                        return_value = 1
        return return_value

def makeNonBlocking(fd):
    fl = fcntl.fcntl(fd, fcntl.F_GETFL)
    try:
        fcntl.fcntl(fd, fcntl.F_SETFL, fl | os.O_NDELAY)
    except AttributeError:
            fcntl.fcntl(fd, fcntl.F_SETFL, fl | os.FNDELAY)

def runCommand(cmd, printout=0, timeout=-1):
    """
    Run command 'cmd'.
    Returns command stdoutput+stderror string on success,
    or None if an error occurred.
    Following recipe on http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/52296
    """

    child = popen2.Popen3(cmd, 1) # capture stdout and stderr from command
    child.tochild.close()             # don't need to talk to child
    outfile = child.fromchild
    outfd = outfile.fileno()
    errfile = child.childerr
    errfd = errfile.fileno()
    makeNonBlocking(outfd)            # don't deadlock!
    makeNonBlocking(errfd)
    outdata = []
    errdata = []
    outeof = erreof = 0

    if timeout > 0 :
        maxwaittime = time.time() + timeout

    err = -1
    while (timeout == -1 or time.time() < maxwaittime):
        ready = select.select([outfd,errfd],[],[]) # wait for input
        if outfd in ready[0]:
            outchunk = outfile.read()
            if outchunk == '': outeof = 1
            outdata.append(outchunk)
        if errfd in ready[0]:
            errchunk = errfile.read()
            if errchunk == '': erreof = 1
            errdata.append(errchunk)
        if outeof and erreof:
            err = child.wait()
            break
        select.select([],[],[],.1) # give a little time for buffers to fill
    if err == -1:
        # kill the pid
        os.kill (child.pid, 9)
        err = child.wait()

    cmd_out = string.join(outdata,"")
    cmd_err = string.join(errdata,"")

    if err:
        return None

    cmd_out = cmd_out + cmd_err
    return cmd_out



def main(argv) :
    """
    lsf_pa_count

    count lsf jobs

    optional parameters:
    --help             :       help
    --debug            :       debug statements
    
    """

    # defaults
    debug = 0

    try:
        opts, args = getopt.getopt(argv, "", ["help", "debug"])
    except getopt.GetoptError:
        print main.__doc__
        sys.exit(2)

    # check command line parameter
    for opt, arg in opts :
        if opt  == "--help" :
            print main.__doc__
            sys.exit()
        elif opt == "--debug" :
            debug = 1
            
    # initialize variables
    processing_pending = 0
    processing_running = 0
    processing_tooLong = 0
    processing_other    = 0
    processing_unknown = 0
    merging_pending = 0
    merging_running = 0
    merging_tooLong = 0
    merging_other    = 0
    merging_unknown = 0

    cleanup_pending = 0
    cleanup_running = 0
    cleanup_tooLong = 0
    cleanup_other    = 0
    cleanup_unknown = 0

    logcollect_pending = 0
    logcollect_running = 0
    logcollect_tooLong = 0
    logcollect_other    = 0
    logcollect_unknown = 0

    queue = 0

    now = time.localtime()

    # check lsf  queue
    cmd = 'bjobs -w'
    cmd_out = runCommand(cmd)
    if cmd_out != None :
        for line in cmd_out.splitlines() :
            try:
                line_content = line.split()
                if debug :
                    print 'LSF line:',line_content
                if os.environ['USER'] == line_content[1].strip() :
                    queue += 1
                    if line_content[6].strip().find('merge') >= 0 :
                        if line_content[2].strip().find("PEND") >= 0 :
                            merging_pending += 1
                        elif line_content[2].strip().find("RUN") >= 0:
                            merging_running += 1
                            start= time.strptime(time.strftime("%Y ",now) + ' '.join(line_content[-3:]),"%Y %b %d %H:%M")
                            if debug :
                                print 'running time: ',(time.mktime(now)-time.mktime(start))
                            if (time.mktime(now)-time.mktime(start)) > 8.*3600.:
                                merging_tooLong += 1
                        else:
                            merging_other += 1
                    elif line_content[6].strip().find('CleanUp') >= 0 :
                        if line_content[2].strip().find("PEND") >= 0 :
                            cleanup_pending += 1
                        elif line_content[2].strip().find("RUN") >= 0:
                            cleanup_running += 1
                            start= time.strptime(time.strftime("%Y ",now) + ' '.join(line_content[-3:]),"%Y %b %d %H:%M")
                            if (time.mktime(now)-time.mktime(start)) > 8.*3600.:
                                cleanup_tooLong += 1
                        else:
                            cleanup_other += 1
                    elif line_content[6].strip().find('LogCollect') >= 0 :
                        if line_content[2].strip().find("PEND") >= 0 :
                            logcollect_pending += 1
                        elif line_content[2].strip().find("RUN") >= 0:
                            logcollect_running += 1
                            start= time.strptime(time.strftime("%Y ",now) + ' '.join(line_content[-3:]),"%Y %b %d %H:%M")
                            if (time.mktime(now)-time.mktime(start)) > 8.*3600.:
                                logcollect_tooLong += 1
                        else:
                            logcollect_other += 1
                    else:
                        if line_content[2].strip().find("PEND") >= 0 :
                            processing_pending += 1
                        elif line_content[2].strip().find("RUN") >= 0:
                            processing_running += 1
                            start= time.strptime(time.strftime("%Y ",now) + ' '.join(line_content[-3:]),"%Y %b %d %H:%M")
                            if (time.mktime(now)-time.mktime(start)) > 8.*3600.:
                                processing_tooLong += 1
                        else:
                            processing_other += 1
            except:
                print 'Cannot parse line:',line

        print ''
        print ' PA LSF queue status for %4d jobs in the queue' % queue
        print ''
        print ' Processing jobs: pending: %4d running: %4d other: %4d' % (processing_pending,processing_running,processing_other)
        print ' Merge      jobs: pending: %4d running: %4d other: %4d' % (merging_pending,merging_running,merging_other)
        print ' CleanUp    jobs: pending: %4d running: %4d other: %4d' % (cleanup_pending,cleanup_running,cleanup_other)
        print ' LogCollect jobs: pending: %4d running: %4d other: %4d' % (logcollect_pending,logcollect_running,logcollect_other)
        print ' --------------------------------------------------------'
        print ' All        jobs: pending: %4d running: %4d other: %4d' % (processing_pending+merging_pending+cleanup_pending+logcollect_pending,processing_running+merging_running+cleanup_running+logcollect_running,processing_other+merging_other+cleanup_other+logcollect_other)
        print ''
        if processing_tooLong > 0:
            print ''
            print ' Processing jobs running for more than 8 hours:     %4d' % processing_tooLong
        if merging_tooLong > 0:
            print ''
            print ' Merge      jobs running for more than 8 hours:     %4d' % merging_tooLong
        if queue != (processing_pending+merging_pending+cleanup_pending+logcollect_pending+processing_running+merging_running+cleanup_running+logcollect_running+processing_other+merging_other+cleanup_other+logcollect_other):
            print ''
            print ' ATTENTION! INCONSISTENT NUMBERS!'

if __name__ == '__main__' :
    main(sys.argv[1:])
