#!/bin/bash

# CMS general setup

if [ "$1" == "cms" ]; then
   echo "CMS software environment"
   . /uscmst1/prod/sw/cms/shrc prod
elif [ "$1" == "nightly" ]; then
   echo "Nightly configuration"
   . /uscmst1/prod/sw/cms/shrc nightly
elif [ "$1" == "crab" ]; then
   echo "CRAB uscmst1 configuration"
   source /uscmst1/prod/grid/CRAB/crab.sh
elif [ "$1" == "crab_local" ]; then
   echo "CRAB local configuration"
   source /uscms/home/gutsche/work/software/CRAB/CRAB/crab.sh
   export DBS_CLIENT_CONFIG=/uscms/home/gutsche/work/software/CRAB/CRAB/external/DBSAPI/DBSAPI/dbs.config
elif [ "$1" == "go" ]; then
   echo "CMS2 working environment"
   . /uscmst1/prod/sw/cms/shrc prod
   cd /uscms/home/gutsche/work/software/TAS/CMSSW_1_6_12/src/CMS2/NtupleMacros/
   eval `scramv1 runtime -sh`
   export CMS2_LOCATION=$CMSSW_BASE/src/CMS2
elif [ "$1" == "dbs" ]; then
   echo "DBS configuration"
   cd /uscms/home/gutsche/work/software/DataCert/DBS/Clients/Python
   source setup.sh 
   cd -
elif [ "$1" == "pa" ]; then
   cd /uscms_data/d1/gutsche/pa/0127
   source start_prodagent.sh 0
   cd PRODAGENT/work
else
   echo "Please give configuration"
fi
