#!/bin/bash

for dir in $*
do
cd $dir
echo "Merge histogram files in $dir"
GutSoftHistogramFileMerger histograms.root *_histograms.root
echo "preparing efficiency plots"
root -b -l -q 'prepareEfficiencyPlots.C("histograms.root")'
echo "preparing rs/ctf comparison plots"
root -b -l -q 'compareTwoHistograms.C("histograms.root")'
echo "Extract timing for $dir"
$CMSSW_BASE/src/GutSoftConfigurations/Scripts/extractTiming --logfile "*.log.gz" > timing.txt
echo "Analyze logfiles for $dir"
$CMSSW_BASE/src/GutSoftConfigurations/Scripts/postAnalysis *.log.gz > analysis.txt
echo "GZip logfiles"
find . -name "*.log" -exec gzip {} \;
cd ..
done
