#!/bin/bash

for dir in $*
do
cd $dir
if [ -f done_postProcessing ];
then
    echo "postProcessing already done"
else
    echo "Merge histogram files in dCache $dir"
    GutSoftHistogramFileMerger histograms.root /pnfs/cms/WAX/resilient/gutsche/condor/$dir/*_histograms_*.root
    echo "preparing efficiency plots"
    root -b -l -q 'prepareEfficiencyPlots.C("histograms.root")'
    echo "preparing rs/ctf comparison plots"
    root -b -l -q 'compareTwoHistograms.C("histograms.root")'
    echo "Extract timing for $dir"
    $CMSSW_BASE/src/GutSoftConfigurations/Scripts/extractTiming --logfile "crab_?_*_*/res/CMSSW*.stdout" > timing.txt
    echo "Analyze logfiles for $dir"
    $CMSSW_BASE/src/GutSoftConfigurations/Scripts/postAnalysis crab_?_*_*/res/CMSSW*.stdout > analysis.txt
    echo "GZip logfiles"
    find . -name "CMSSW*.stdout" -exec gzip {} \;
    echo "Remove bossCache"
    rm -rf crab_*/share/.boss*
    echo "Touch done_postProcessing"
    touch done_postProcessing
fi
cd ..
done
