#!/usr/bin/python

import sys, os, getopt, glob

def main(argv) :
    """
    
    postAnalysis
    
    check how many events have been processed and list errors and warnings

    parameters: <logfiles>
    
    """

    warnings = []
    errors = []
    runs = {}

    filenames = argv[0:]
    for filename in filenames :
        if os.path.exists(filename) :
            file = open(filename)
            line = file.readline()
            while line :
                tmp = ''
                if line.find('MSG-w') >= 0 :
                    tmp += line
                    line = file.readline()
                    while line[0] != '%' :
                        tmp += line
                        line = file.readline()
                    warnings.append(tmp)
                if line.find('MSG-e') >= 0 :
                    tmp += line
                    line = file.readline()
                    while line[0] != '%' :
                        tmp += line
                        line = file.readline()
                    errors.append(tmp)
                if line.find('Begin processing') >= 0 :
                    try:
                        run = int(line.split()[-3].strip().split(',')[0].strip())
                        event = int(line.split()[-1].strip())
                        if run in runs.keys() :
                            runs[run].append(event)
                        else :
                            runs[run] = [event]
                    except:
                        tmp = ''
                line = file.readline()

        else :
            print 'File:',filename,'does not exist!'

        
    # print warnings
    counter = 0
    for warning in warnings :
        counter += 1
        print ''
        print 'Warning:',counter
        print ''
        print warning

    # print errors
    counter = 0
    for error in errors :
        counter += 1
        print ''
        print 'Error:',counter
        print ''
        print error

    # print run and event summary
    print ''
    counter = 0
    for run in runs.keys():
        print 'Run:',run,'Events:',runs[run]
        counter += len(runs[run])

    print ''
    print 'Processed',len(runs.keys()),' Run(s) with total',counter,'Event(s).'        

if __name__ == '__main__' :
    main(sys.argv[1:])
