#!/usr/bin/env python2.4

import sys, os, getopt
import DBSAPI.dbsApi

def main(argv) :

    #dbs                = 'http://cmssrv46.fnal.gov:8080/DBS/servlet/DBSServlet'
    #dbs                = 'http://cmsdbsprod.cern.ch/cms_dbs_prod_global/servlet/DBSServlet'
    #dbs                = 'http://cmssrv17.fnal.gov:8989/DBS116Oracle/servlet/DBSServlet'
    dbs                = 'http://cmst0dbs.cern.ch/cms_dbs_prod_tier0/servlet/DBSServlet'
    se                 = '*'
    datasetpath        = '/Cosmics/CRUZET2_CRUZET2_V1_v2/RECO'
    debug              = 0
    # init dbs
    args = {}
    args['url']   = dbs
    args['level'] = 'CRITICAL'

    api = DBSAPI.dbsApi.DbsApi(args)
    #print api.listAlgorithms(patternVer="CMSSW_2_0_*", patternFam="*", patternExe="*", patternPS="*")
    datasets = api. listProcessedDatasets(patternPrim="Cosmics", patternDT="RAW", patternProc="CRUZET3-v1")
    for dataset in datasets:
        print dataset['PrimaryDataset']['Name'],dataset['Name'],dataset['TierList']
        print dataset['AlgoList']
    #blocks = api.listBlocks(dataset=datasetpath,block_name="*",storage_element_name=se);
    #for block in blocks:
        #files = api.listFiles(blockName=block['Name'])
        #print files[0]['LogicalFileName'],block['Name'],len(files)


        #for file in files:
        #    filenames.append(file['LogicalFileName'])
        #    events += file['NumberOfEvents']
        #    size   += file['FileSize']

if __name__ == '__main__' :
    main(sys.argv[1:])

