#!/usr/bin/env python2.4

import sys, os, getopt
import DBSAPI.dbsApi

def main(argv) :

    #dbs                = 'http://cmssrv46.fnal.gov:8080/DBS/servlet/DBSServlet'
    dbs                = 'http://cmsdbsprod.cern.ch/cms_dbs_prod_global/servlet/DBSServlet'
    se                 = '*'
    datasetpath        = '/MinBias/CSA08_STARTUP_V2_v2/GEN-SIM-RECO'
    debug              = 0
    # init dbs
    args = {}
    args['url']   = dbs
    args['level'] = 'CRITICAL'

    api = DBSAPI.dbsApi.DbsApi(args)
    blocks = api.listBlocks(dataset=datasetpath,block_name="*",storage_element_name=se);
    for block in blocks:
        files = api.listFiles(blockName=block['Name'])
        print files[0]['LogicalFileName'],block['Name'],len(files)


        #for file in files:
        #    filenames.append(file['LogicalFileName'])
        #    events += file['NumberOfEvents']
        #    size   += file['FileSize']

if __name__ == '__main__' :
    main(sys.argv[1:])

