#!/bin/sh

for dir in $*
do
cd $dir
echo ""
echo "delete directory in ~/transfer/$dir"
rm -rf ~/transfer/$dir
echo "make directory ~/transfer/$dir"
mkdir -p ~/transfer/$dir
echo "copy analysis.txt to ~/transfer/$dir"
cp analysis.txt ~/transfer/$dir
echo "copy timing.txt to ~/transfer/$dir"
cp timing.txt ~/transfer/$dir
echo "copy *.gif to ~/transfer/$dir"
cp *.gif ~/transfer/$dir
cd ..
done
