Int_t           evt_nmus;
Int_t           evt_ntrks;
Int_t           evt_run;
Int_t           evt_event;
Int_t           evt_nels;
Int_t           evt_njets;
Int_t           evt_ncorrectedjets;
vector<int>     *mus_validHits;
vector<int>     *mus_lostHits;
vector<int>     *mus_mc_id;
vector<int>     *mus_mc_motherid;
vector<int>     *mus_nmatches;
vector<int>     *mus_iso03_ntrk;
vector<int>     *mus_iso05_ntrk;
vector<int>     *mus_pid_TMLastStationLoose;
vector<int>     *mus_pid_TMLastStationTight;
vector<int>     *mus_pid_TM2DCompatibilityLoose;
vector<int>     *mus_pid_TM2DCompatibilityTight;
vector<int>     *mus_gfit_validHits;
vector<int>     *mus_map_LooseTrackerMuons;
vector<int>     *mus_map_TightTrackerMuons;
vector<int>     *trks_validHits;
vector<int>     *trks_lostHits;
vector<int>     *trks_mc_id;
vector<int>     *trks_mc_motherid;
vector<int>     *els_validHits;
vector<int>     *els_lostHits;
vector<int>     *els_mc_id;
vector<int>     *els_mc_motherid;
vector<int>     *els_nSeed;
vector<int>     *els_class;
vector<int>     *els_looseId;
vector<int>     *els_tightId;
vector<int>     *genps_id;
vector<int>     *jets_mc_id;
vector<int>     *corrected_jets_mc_id;
Float_t         evt_met;
Float_t         evt_metPhi;
Float_t         evt_sumEt;
Float_t         evt_metSig;
Float_t         evt_met_jetcorr;
Float_t         metphi_jetcorr;
Float_t         gen_met;
Float_t         gen_metPhi;
vector<float>   *mus_d0;
vector<float>   *mus_z0;
vector<float>   *mus_vertexphi;
vector<float>   *mus_chi2;
vector<float>   *mus_ndof;
vector<float>   *mus_d0Err;
vector<float>   *mus_z0Err;
vector<float>   *mus_ptErr;
vector<float>   *mus_etaErr;
vector<float>   *mus_phiErr;
vector<float>   *mus_e_em;
vector<float>   *mus_e_had;
vector<float>   *mus_e_ho;
vector<float>   *mus_e_emS9;
vector<float>   *mus_e_hadS9;
vector<float>   *mus_e_hoS9;
vector<float>   *mus_iso03_sumPt;
vector<float>   *mus_iso03_emEt;
vector<float>   *mus_iso03_hadEt;
vector<float>   *mus_iso03_hoEt;
vector<float>   *mus_iso05_sumPt;
vector<float>   *mus_iso05_emEt;
vector<float>   *mus_iso05_hadEt;
vector<float>   *mus_iso05_hoEt;
vector<float>   *mus_gfit_chi2;
vector<float>   *mus_gfit_ndof;
vector<float>   *trks_d0;
vector<float>   *trks_z0;
vector<float>   *trks_vertexphi;
vector<float>   *trks_chi2;
vector<float>   *trks_ndof;
vector<float>   *trks_d0Err;
vector<float>   *trks_z0Err;
vector<float>   *trks_ptErr;
vector<float>   *trks_etaErr;
vector<float>   *trks_phiErr;
vector<float>   *els_d0;
vector<float>   *els_z0;
vector<float>   *els_vertexphi;
vector<float>   *els_chi2;
vector<float>   *els_ndof;
vector<float>   *els_d0Err;
vector<float>   *els_z0Err;
vector<float>   *els_ptErr;
vector<float>   *els_etaErr;
vector<float>   *els_phiErr;
vector<float>   *els_hOverE;
vector<float>   *els_eOverPIn;
vector<float>   *els_eSeedOverPOut;
vector<float>   *els_fBrem;
vector<float>   *els_dEtaIn;
vector<float>   *els_dEtaOut;
vector<float>   *els_dPhiIn;
vector<float>   *els_dPhiOut;
vector<float>   *els_ESc;
vector<float>   *els_ESc_raw;
vector<float>   *els_e3x3;
vector<float>   *els_e5x5;
vector<float>   *els_ESeed;
vector<float>   *els_sigmaPhiPhi;
vector<float>   *els_sigmaEtaEta;
vector<float>   *els_tkIso;
vector<float>   *genjs_emEnergy;
vector<float>   *genjs_hadEnergy;
vector<float>   *genjs_invEnergy;
vector<float>   *genjs_otherEnergy;
vector<float>   *jets_emFrac;
vector<float>   *jets_chFrac;
vector<float>   *jets_mc_emEnergy;
vector<float>   *jets_mc_hadEnergy;
vector<float>   *jets_mc_invEnergy;
vector<float>   *jets_mc_otherEnergy;
vector<float>   *jets_cor;
vector<float>   *corrected_jets_emFrac;
vector<float>   *corrected_jets_chFrac;
vector<float>   *corrected_jets_mc_emEnergy;
vector<float>   *corrected_jets_mc_hadEnergy;
vector<float>   *corrected_jets_mc_invEnergy;
vector<float>   *corrected_jets_mc_otherEnergy;
vector<float>   *corrected_jets_cor;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*mus_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*mus_trk_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*mus_mc_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*trks_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*trks_trk_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*trks_mc_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*els_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*els_trk_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*els_mc_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*genps_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*genjs_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*jets_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*jets_mc_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*jets_mc_gp_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*corrected_jets_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*corrected_jets_mc_p4;
vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*corrected_jets_mc_gp_p4;


