#!/bin/bash

cfg=$1
jobs=$2
name=`echo $cfg | sed s/.cfg//`
echo ""
echo "name : $name"
echo ""
time crab -create $2 -submit $2 -cfg $cfg
rm -f $name
crabdir=`ls -td crab_* | head -n 1`
rm -f $name
ln -s $crabdir $name
