#!/usr/bin/env sh
#
# 07-Dec-2005
# Stefano Lacaprara  <lacaprara@pd.infn.it>  INFN Padova
#
# Wrapper script for crab.py
#
if [ -z "$PYTHONPATH" ]; then
  export PYTHONPATH=${SKIMDIR}:${SKIMPSETPYTHON}
else
  export PYTHONPATH=${SKIMDIR}:${SKIMPSETPYTHON}:${PYTHONPATH}
fi

/usr/bin/env python $SKIMDIR/skim.py $*
