	vector<int>	*mus_validHits;
	vector<int>	*mus_lostHits;
	vector<int>	*mus_mc_id;
	vector<int>	*mus_mc_motherid;
	vector<int>	*mus_nmatches;
	vector<int>	*mus_iso03_ntrk;
	vector<int>	*mus_iso05_ntrk;
	vector<int>	*mus_pid_TMLastStationLoose;
	vector<int>	*mus_pid_TMLastStationTight;
	vector<int>	*mus_pid_TM2DCompatibilityLoose;
	vector<int>	*mus_pid_TM2DCompatibilityTight;
	vector<int>	*mus_gfit_validHits;
	vector<int>	*mus_map_LooseTrackerMuons;
	vector<int>	*mus_map_TightTrackerMuons;
	vector<int>	*trks_validHits;
	vector<int>	*trks_lostHits;
	vector<int>	*trks_mc_id;
	vector<int>	*trks_mc_motherid;
	vector<int>	*els_validHits;
	vector<int>	*els_lostHits;
	vector<int>	*els_mc_id;
	vector<int>	*els_mc_motherid;
	vector<int>	*els_nSeed;
	vector<int>	*els_class;
	vector<int>	*els_looseId;
	vector<int>	*els_tightId;
	vector<int>	*genps_id;
	vector<int>	*hyp_jets_mc_id;
	vector<int>	*hyp_other_jets_mc_id;
	vector<float>	*mus_d0;
	vector<float>	*mus_z0;
	vector<float>	*mus_vertexphi;
	vector<float>	*mus_chi2;
	vector<float>	*mus_ndof;
	vector<float>	*mus_d0Err;
	vector<float>	*mus_z0Err;
	vector<float>	*mus_ptErr;
	vector<float>	*mus_etaErr;
	vector<float>	*mus_phiErr;
	vector<float>	*mus_e_em;
	vector<float>	*mus_e_had;
	vector<float>	*mus_e_ho;
	vector<float>	*mus_e_emS9;
	vector<float>	*mus_e_hadS9;
	vector<float>	*mus_e_hoS9;
	vector<float>	*mus_iso03_sumPt;
	vector<float>	*mus_iso03_emEt;
	vector<float>	*mus_iso03_hadEt;
	vector<float>	*mus_iso03_hoEt;
	vector<float>	*mus_iso05_sumPt;
	vector<float>	*mus_iso05_emEt;
	vector<float>	*mus_iso05_hadEt;
	vector<float>	*mus_iso05_hoEt;
	vector<float>	*mus_gfit_chi2;
	vector<float>	*mus_gfit_ndof;
	vector<float>	*trks_d0;
	vector<float>	*trks_z0;
	vector<float>	*trks_vertexphi;
	vector<float>	*trks_chi2;
	vector<float>	*trks_ndof;
	vector<float>	*trks_d0Err;
	vector<float>	*trks_z0Err;
	vector<float>	*trks_ptErr;
	vector<float>	*trks_etaErr;
	vector<float>	*trks_phiErr;
	vector<float>	*els_d0;
	vector<float>	*els_z0;
	vector<float>	*els_vertexphi;
	vector<float>	*els_chi2;
	vector<float>	*els_ndof;
	vector<float>	*els_d0Err;
	vector<float>	*els_z0Err;
	vector<float>	*els_ptErr;
	vector<float>	*els_etaErr;
	vector<float>	*els_phiErr;
	vector<float>	*els_hOverE;
	vector<float>	*els_eOverPIn;
	vector<float>	*els_eSeedOverPOut;
	vector<float>	*els_fBrem;
	vector<float>	*els_dEtaIn;
	vector<float>	*els_dEtaOut;
	vector<float>	*els_dPhiIn;
	vector<float>	*els_dPhiOut;
	vector<float>	*els_ESc;
	vector<float>	*els_ESc_raw;
	vector<float>	*els_e3x3;
	vector<float>	*els_e5x5;
	vector<float>	*els_ESeed;
	vector<float>	*els_sigmaPhiPhi;
	vector<float>	*els_sigmaEtaEta;
	vector<float>	*els_tkIso;
	vector<float>	*genjs_emEnergy;
	vector<float>	*genjs_hadEnergy;
	vector<float>	*genjs_invEnergy;
	vector<float>	*genjs_otherEnergy;
	vector<float>	*hyp_jets_emFrac;
	vector<float>	*hyp_jets_chFrac;
	vector<float>	*hyp_jets_mc_emEnergy;
	vector<float>	*hyp_jets_mc_hadEnergy;
	vector<float>	*hyp_jets_mc_invEnergy;
	vector<float>	*hyp_jets_mc_otherEnergy;
	vector<float>	*hyp_jets_cor;
	vector<float>	*hyp_other_jets_emFrac;
	vector<float>	*hyp_other_jets_chFrac;
	vector<float>	*hyp_other_jets_mc_emEnergy;
	vector<float>	*hyp_other_jets_mc_hadEnergy;
	vector<float>	*hyp_other_jets_mc_invEnergy;
	vector<float>	*hyp_other_jets_mc_otherEnergy;
	vector<float>	*hyp_other_jets_cor;
	ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> >	*hyp_lt_p4;
	ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> >	*hyp_lt_trk_p4;
	ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> >	*hyp_lt_mc_p4;
	ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> >	*hyp_ll_p4;
	ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> >	*hyp_ll_trk_p4;
	ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> >	*hyp_ll_mc_p4;
	ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> >	*hyp_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*mus_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*mus_trk_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*mus_mc_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*trks_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*trks_trk_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*trks_mc_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*els_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*els_trk_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*els_mc_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*genps_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*genjs_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*hyp_jets_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*hyp_jets_mc_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*hyp_jets_mc_gp_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*hyp_other_jets_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*hyp_other_jets_mc_p4;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > >	*hyp_other_jets_mc_gp_p4;
	float	evt_scale1fb;
   int           evt_nmus;
   int           evt_ntrks;
   int           evt_run;
   int           evt_event;
   int           evt_nels;
   int           hyp_lt_validHits;
   int           hyp_lt_lostHits;
   int           hyp_lt_mc_id;
   int           hyp_lt_mc_motherid;
   int           hyp_ll_validHits;
   int           hyp_ll_lostHits;
   int           hyp_ll_mc_id;
   int           hyp_ll_mc_motherid;
   int           hyp_type;
   int           hyp_njets;
   int           hyp_nojets;
   int           hyp_lt_index;
   int           hyp_ll_index;
   int           hyp_lt_id;
   int           hyp_ll_id;
   int           evt_nCand;
   float         evt_met;
   float         evt_metPhi;
   float         evt_sumEt;
   float         evt_metSig;
   float         evt_met_jetcorr;
   float         metphi_jetcorr;
   float         gen_met;
   float         gen_metPhi;
   float         hyp_lt_d0;
   float         hyp_lt_z0;
   float         hyp_lt_vertexphi;
   float         hyp_lt_chi2;
   float         hyp_lt_ndof;
   float         hyp_lt_d0Err;
   float         hyp_lt_z0Err;
   float         hyp_lt_ptErr;
   float         hyp_lt_etaErr;
   float         hyp_lt_phiErr;
   float         hyp_ll_d0;
   float         hyp_ll_z0;
   float         hyp_ll_vertexphi;
   float         hyp_ll_chi2;
   float         hyp_ll_ndof;
   float         hyp_ll_d0Err;
   float         hyp_ll_z0Err;
   float         hyp_ll_ptErr;
   float         hyp_ll_etaErr;
   float         hyp_ll_phiErr;
   float         hyp_met;
   float         hyp_metPhi;
   float         hyp_metCone;
   float         hyp_metPhiCone;
   float         hyp_metNoCalo;
   float         hyp_metPhiNoCalo;
   float         hyp_metAll;
   float         hyp_metPhiAll;
   float         hyp_metJes5;
   float         hyp_metPhiJes5;
   float         hyp_metJes10;
   float         hyp_metPhiJes10;
   float         hyp_metJes15;
   float         hyp_metPhiJes15;
   float         hyp_metJes30;
   float         hyp_metPhiJes30;
   float         hyp_metJes50;
   float         hyp_metPhiJes50;
   float         hyp_metDPhiJet10;
   float         hyp_metDPhiJet15;
   float         hyp_metDPhiJet20;
   float         hyp_metDPhiTrk10;
   float         hyp_metDPhiTrk25;
   float         hyp_metDPhiTrk50;
   float         hyp_lt_iso;
   float         hyp_ll_iso;
   float         evt_xsec_incl;
   float         evt_xsec_excl;
