#!/bin/bash

condor_submit simulate-single_mu_pt_100_negative.jdl
condor_submit simulate-single_mu_pt_100_positive.jdl
condor_submit simulate-single_mu_pt_10_negative.jdl
condor_submit simulate-single_mu_pt_10_positive.jdl
condor_submit simulate-single_mu_pt_15_negative.jdl
condor_submit simulate-single_mu_pt_15_positive.jdl
condor_submit simulate-single_mu_pt_1_negative.jdl
condor_submit simulate-single_mu_pt_1_positive.jdl
condor_submit simulate-single_mu_pt_25_negative.jdl
condor_submit simulate-single_mu_pt_25_positive.jdl
condor_submit simulate-single_mu_pt_2_negative.jdl
condor_submit simulate-single_mu_pt_2_positive.jdl
condor_submit simulate-single_mu_pt_50_negative.jdl
condor_submit simulate-single_mu_pt_50_positive.jdl
condor_submit simulate-single_mu_pt_5_negative.jdl
condor_submit simulate-single_mu_pt_5_positive.jdl
