# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2012-01-01 and block.createdate < 2012-02-01" > data_2012_jan_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2012-01-01 and block.createdate < 2012-02-01" > data_2012_jan_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2012-01-01 and block.createdate < 2012-02-01" > data_2012_jan_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2012-01-01 and block.createdate < 2012-02-01" > data_2012_jan_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2012-01-01 and block.createdate < 2012-02-01" > data_2012_jan_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2012-02-01 and block.createdate < 2012-03-01" > data_2012_feb_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2012-02-01 and block.createdate < 2012-03-01" > data_2012_feb_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2012-02-01 and block.createdate < 2012-03-01" > data_2012_feb_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2012-02-01 and block.createdate < 2012-03-01" > data_2012_feb_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2012-02-01 and block.createdate < 2012-03-01" > data_2012_feb_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2012-03-01 and block.createdate < 2012-04-01" > data_2012_mar_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2012-03-01 and block.createdate < 2012-04-01" > data_2012_mar_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2012-03-01 and block.createdate < 2012-04-01" > data_2012_mar_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2012-03-01 and block.createdate < 2012-04-01" > data_2012_mar_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2012-03-01 and block.createdate < 2012-04-01" > data_2012_mar_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2012-04-01 and block.createdate < 2012-05-01" > data_2012_apr_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2012-04-01 and block.createdate < 2012-05-01" > data_2012_apr_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2012-04-01 and block.createdate < 2012-05-01" > data_2012_apr_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2012-04-01 and block.createdate < 2012-05-01" > data_2012_apr_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2012-04-01 and block.createdate < 2012-05-01" > data_2012_apr_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2012-05-01 and block.createdate < 2012-06-01" > data_2012_may_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2012-05-01 and block.createdate < 2012-06-01" > data_2012_may_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2012-05-01 and block.createdate < 2012-06-01" > data_2012_may_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2012-05-01 and block.createdate < 2012-06-01" > data_2012_may_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2012-05-01 and block.createdate < 2012-06-01" > data_2012_may_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2012-06-01 and block.createdate < 2012-07-01" > data_2012_jun_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2012-06-01 and block.createdate < 2012-07-01" > data_2012_jun_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2012-06-01 and block.createdate < 2012-07-01" > data_2012_jun_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2012-06-01 and block.createdate < 2012-07-01" > data_2012_jun_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2012-06-01 and block.createdate < 2012-07-01" > data_2012_jun_user.blocks
# 
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2012-07-01 and block.createdate < 2012-08-01" > data_2012_jul_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2012-07-01 and block.createdate < 2012-08-01" > data_2012_jul_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2012-07-01 and block.createdate < 2012-08-01" > data_2012_jul_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2012-07-01 and block.createdate < 2012-08-01" > data_2012_jul_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2012-07-01 and block.createdate < 2012-08-01" > data_2012_jul_user.blocks

# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2012-08-01 and block.createdate < 2012-09-01" > data_2012_aug_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2012-08-01 and block.createdate < 2012-09-01" > data_2012_aug_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2012-08-01 and block.createdate < 2012-09-01" > data_2012_aug_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2012-08-01 and block.createdate < 2012-09-01" > data_2012_aug_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2012-08-01 and block.createdate < 2012-09-01" > data_2012_aug_user.blocks

# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2012-09-01 and block.createdate < 2012-10-01" > data_2012_sep_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2012-09-01 and block.createdate < 2012-10-01" > data_2012_sep_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2012-09-01 and block.createdate < 2012-10-01" > data_2012_sep_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2012-09-01 and block.createdate < 2012-10-01" > data_2012_sep_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2012-09-01 and block.createdate < 2012-10-01" > data_2012_sep_user.blocks

# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2012-10-01 and block.createdate < 2012-11-01" > data_2012_oct_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2012-10-01 and block.createdate < 2012-11-01" > data_2012_oct_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2012-10-01 and block.createdate < 2012-11-01" > data_2012_oct_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2012-10-01 and block.createdate < 2012-11-01" > data_2012_oct_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2012-10-01 and block.createdate < 2012-11-01" > data_2012_oct_user.blocks

# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2012-11-01 and block.createdate < 2012-12-01" > data_2012_nov_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2012-11-01 and block.createdate < 2012-12-01" > data_2012_nov_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2012-11-01 and block.createdate < 2012-12-01" > data_2012_nov_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2012-11-01 and block.createdate < 2012-12-01" > data_2012_nov_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2012-11-01 and block.createdate < 2012-12-01" > data_2012_nov_user.blocks

# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW and block.createdate >= 2012-12-01 and block.createdate < 2013-01-01" > data_2012_dec_raw.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RECO and block.createdate >= 2012-12-01 and block.createdate < 2013-01-01" > data_2012_dec_reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = AOD and block.createdate >= 2012-12-01 and block.createdate < 2013-01-01" > data_2012_dec_aod.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = RAW-RECO and block.createdate >= 2012-12-01 and block.createdate < 2013-01-01" > data_2012_dec_raw-reco.blocks
# dbs search --noheader --production --query="find block,block.size,block.numevents,block.createdate where tier = USER and block.createdate >= 2012-12-01 and block.createdate < 2013-01-01" > data_2012_dec_user.blocks


rm -f statistics.txt

cat data_2012_jan_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting'  | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2012 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jan_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2012 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jan_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2012 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jan_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2012 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jan_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2012 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jan_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2012 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jan_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2012 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jan_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2012 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jan_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2012 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jan_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2012 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jan_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "January 2012 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt

cat data_2012_feb_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2012 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_feb_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2012 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_feb_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2012 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_feb_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2012 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_feb_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2012 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_feb_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2012 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_feb_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2012 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_feb_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2012 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_feb_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2012 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_feb_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2012 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_feb_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "Feburary 2012 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt

cat data_2012_mar_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2012 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_mar_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2012 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_mar_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2012 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_mar_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2012 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_mar_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2012 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_mar_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2012 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_mar_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2012 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_mar_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2012 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_mar_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2012 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_mar_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2012 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_mar_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "March 2012 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt

cat data_2012_apr_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2012 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_apr_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2012 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_apr_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2012 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_apr_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2012 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_apr_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2012 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_apr_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2012 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_apr_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2012 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_apr_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2012 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_apr_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2012 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_apr_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2012 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_apr_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "April 2012 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt

cat data_2012_may_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2012 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_may_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2012 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_may_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2012 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_may_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2012 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_may_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2012 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_may_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2012 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_may_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2012 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_may_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2012 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_may_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2012 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_may_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2012 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_may_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "May 2012 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt

cat data_2012_jun_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2012 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jun_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2012 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jun_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2012 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jun_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2012 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jun_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2012 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jun_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2012 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jun_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2012 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jun_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2012 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jun_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2012 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jun_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2012 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jun_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "June 2012 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt

cat data_2012_jul_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2012 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jul_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2012 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jul_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2012 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jul_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2012 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jul_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2012 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jul_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2012 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jul_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2012 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jul_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2012 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jul_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2012 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jul_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2012 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
cat data_2012_jul_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "July 2012 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt

# cat data_2012_aug_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2012 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_aug_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2012 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_aug_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2012 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_aug_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2012 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_aug_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2012 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_aug_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2012 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_aug_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2012 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_aug_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2012 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_aug_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2012 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_aug_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2012 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_aug_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "August 2012 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# 
# cat data_2012_sep_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2012 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_sep_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2012 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_sep_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2012 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_sep_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2012 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_sep_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2012 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_sep_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2012 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_sep_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2012 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_sep_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2012 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_sep_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2012 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_sep_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2012 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_sep_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "September 2012 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# 
# cat data_2012_oct_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2012 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_oct_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2012 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_oct_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2012 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_oct_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2012 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_oct_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2012 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_oct_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2012 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_oct_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2012 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_oct_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2012 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_oct_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2012 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_oct_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2012 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_oct_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "October 2012 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# 
# cat data_2012_nov_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2012 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_nov_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2012 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_nov_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2012 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_nov_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2012 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_nov_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2012 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_nov_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2012 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_nov_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2012 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_nov_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2012 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_nov_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2012 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_nov_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2012 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_nov_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "November 2012 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# 
# cat data_2012_dec_raw.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2012 RAW: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_dec_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2012 PromptReco RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_dec_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2012 PromptSkim RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_dec_reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2012 NonPrompt RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_dec_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptReco | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2012 PromptReco AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_dec_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2012 PromptSkim AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_dec_aod.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2012 NonPrompt AOD: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_dec_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2012 PromptSkim RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_dec_raw-reco.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2012 NonPrompt RAW-RECO: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_dec_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -i PromptSkim | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2012 PromptSkim USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt
# cat data_2012_dec_user.blocks | grep -vi test | grep -vi backfill | grep -vi StoreResults | grep -vi 'monitor' | grep -v 'Error/' | grep -v 'Scouting' | grep -v 'MiniDaq' | grep -vi '/Alca' | grep -v 'L1Accept' | grep -v '/Hcal' | grep -vi 'express' | grep -v 'Interfill' | grep -vi Prompt | grep Run2012 | awk '{SUM1+=$2} {SUM2+=$3} END {print "December 2012 NonPrompt USER: Size [TB]: "SUM1/1000000000000" Events: "SUM2}' >> statistics.txt


