#!/bin/bash

./publish.py RelValInjector:SetCurrentRelease CMSSW_1_5_0
./publish.py RelValInjector:SetCurrentArch slc4_ia32_gcc345
./publish.py RelValInjector:SetCurrentCMSPath /uscmst1/prod/sw/cmssw

./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSamples/DevelopmentSample150BJets120_170.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150BJets120_170_LowLumiPileup.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150MinBias.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleEPt100Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleEPt100Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleEPt10Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleEPt10Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleEPt1Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleEPt1Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleEPt25Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleEPt25Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleEPt2Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleEPt2Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleEPt5Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleEPt5Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150Singlegamma_pt_100.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150Singlegamma_pt_10.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150Singlegamma_pt_55.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150Singlegamma_pt_5.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleMuPt100Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleMuPt100Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleMuPt10Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleMuPt10Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleMuPt1Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleMuPt1Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleMuPt25Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleMuPt25Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleMuPt2Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleMuPt2Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleMuPt5Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SingleMuPt5Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SinglePiPt100Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SinglePiPt100Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SinglePiPt10Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SinglePiPt10Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SinglePiPt1Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SinglePiPt1Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SinglePiPt25Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SinglePiPt25Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SinglePiPt2Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SinglePiPt2Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SinglePiPt5Minus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150SinglePiPt5Plus.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150TTBar.xml
./publish.py RelValInjector:Inject  /uscms/home/gutsche/work/software/RoadSearchTracking/CMSSW_1_5_0/src/GutSoftConfigurations/DevelopmentSample150TTBarLowLumiPileup.xml
