#!/bin/bash

cp simulation.cfg single_mu_pt_1_minus.cfg
cp simulation.cfg single_mu_pt_2_minus.cfg
cp simulation.cfg single_mu_pt_5_minus.cfg
cp simulation.cfg single_mu_pt_10_minus.cfg
cp simulation.cfg single_mu_pt_25_minus.cfg
cp simulation.cfg single_mu_pt_100_minus.cfg
cp simulation.cfg single_mu_pt_1_plus.cfg
cp simulation.cfg single_mu_pt_2_plus.cfg
cp simulation.cfg single_mu_pt_5_plus.cfg
cp simulation.cfg single_mu_pt_10_plus.cfg
cp simulation.cfg single_mu_pt_25_plus.cfg
cp simulation.cfg single_mu_pt_100_plus.cfg
cp simulation.cfg single_e_pt_1_minus.cfg
cp simulation.cfg single_e_pt_2_minus.cfg
cp simulation.cfg single_e_pt_5_minus.cfg
cp simulation.cfg single_e_pt_10_minus.cfg
cp simulation.cfg single_e_pt_25_minus.cfg
cp simulation.cfg single_e_pt_100_minus.cfg
cp simulation.cfg single_e_pt_1_plus.cfg
cp simulation.cfg single_e_pt_2_plus.cfg
cp simulation.cfg single_e_pt_5_plus.cfg
cp simulation.cfg single_e_pt_10_plus.cfg
cp simulation.cfg single_e_pt_25_plus.cfg
cp simulation.cfg single_e_pt_100_plus.cfg
cp simulation.cfg single_pi_pt_1_minus.cfg
cp simulation.cfg single_pi_pt_2_minus.cfg
cp simulation.cfg single_pi_pt_5_minus.cfg
cp simulation.cfg single_pi_pt_10_minus.cfg
cp simulation.cfg single_pi_pt_25_minus.cfg
cp simulation.cfg single_pi_pt_100_minus.cfg
cp simulation.cfg single_pi_pt_1_plus.cfg
cp simulation.cfg single_pi_pt_2_plus.cfg
cp simulation.cfg single_pi_pt_5_plus.cfg
cp simulation.cfg single_pi_pt_10_plus.cfg
cp simulation.cfg single_pi_pt_25_plus.cfg
cp simulation.cfg single_pi_pt_100_plus.cfg
cp simulation.cfg single_gamma_pt_5.cfg
cp simulation.cfg single_gamma_pt_10.cfg
cp simulation.cfg single_gamma_pt_55.cfg
cp simulation.cfg single_gamma_pt_100.cfg
cp simulation.cfg minbias.cfg
cp simulation.cfg bjets_120_170.cfg
cp simulation.cfg ttbar.cfg
cp simulation.cfg bjets_120_170_lowlumipileup.cfg
cp simulation.cfg ttbar_lowlumipileup.cfg
