#!/bin/bash

./prepareWorkflow.py --events 10000 --speed-category Slow --cmssw-version $1 --parameter-set DevelopmentSampleBJets120_170.cfg
./prepareWorkflow.py --events 10000 --speed-category Slow --cmssw-version $1 --parameter-set DevelopmentSampleBJets120_170_LowLumiPileup.cfg
./prepareWorkflow.py --events 10000 --speed-category Slow --cmssw-version $1 --parameter-set DevelopmentSampleMinBias.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleEPt100Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleEPt100Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleEPt10Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleEPt10Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleEPt1Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleEPt1Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleEPt25Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleEPt25Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleEPt2Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleEPt2Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleEPt5Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleEPt5Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglegamma_pt_100.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglegamma_pt_10.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglegamma_pt_55.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglegamma_pt_5.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleMuPt100Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleMuPt100Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleMuPt10Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleMuPt10Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleMuPt1Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleMuPt1Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleMuPt25Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleMuPt25Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleMuPt2Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleMuPt2Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleMuPt5Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSingleMuPt5Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglePiPt100Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglePiPt100Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglePiPt10Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglePiPt10Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglePiPt1Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglePiPt1Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglePiPt25Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglePiPt25Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglePiPt2Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglePiPt2Plus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglePiPt5Minus.cfg
./prepareWorkflow.py --events 25000 --speed-category Fast --cmssw-version $1 --parameter-set DevelopmentSampleSinglePiPt5Plus.cfg
